---
- hosts: all
  become: yes
  gather_facts: no
  tasks:
  - name: Install epel-relese
    yum:
      name: epel-release
      state: present
  - name: setup locale
    copy:
      src: locale.conf
      dest: /etc/locale.conf
      owner: root
      group: root
      mode: 0644
  - name: say Network Manager do NOT touch resolv.conf
    copy:
      src: roles/dns/files/NetworkManager.conf
      dest: /etc/NetworkManager/NetworkManager.conf
      owner: root
      group: root
      mode: 0644
  - name: reload config NetworkManager
    service:
      name: NetworkManager
      daemon_reload: yes
- hosts: ns
  become: yes
  gather_facts: no
  roles:
    - { role: dns }
    - { role: ntp }
    - { role: postfix }
    - { role: dovecot }
- hosts: client
  become: yes
  gather_facts: no
  tasks:
  - name: copy resolv.conf to client
    copy:
      src: roles/dns/files/resolv.conf
      dest: /etc/resolv.conf
      owner: root
      group: root
      mode: 0644
  - name: Install alpine mail client
    yum:
      name: alpine
      state: present
  - name: copy .pinerc to client
    copy:
      src: roles/dovecot/files/.pinerc
      dest: /home/vagrant/.pinerc
      owner: root
      group: root
      mode: 0644
- hosts: client
  become: yes
  gather_facts: no
  roles:
    - { role: ntp-client }
...